#基础镜像
FROM hhyghost/jdk8u211

#作者
MAINTAINER huanghoayu 393606325@qq.com

#添加文件
ADD ./demo-0.0.1-SNAPSHOT.jar /usr/local/demo-0.0.1-SNAPSHOT.jar

RUN chmod u+x /usr/local/demo-0.0.1-SNAPSHOT.jar

#开放端口
EXPOSE 8080

#启动时执行的命令
CMD ["/bin/bash"]

#启动时执行的命令
ENTRYPOINT ["java","-jar -Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200","/usr/local/demo-0.0.1-SNAPSHOT.jar"]
